config/routes.rb
  Rails.application.routes.draw do
    

  get 'likes/create'

  get 'likes/delete'

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/dize',    to: 'static_pages#dize'
  get  '/diza',    to: 'static_pages#diza'
  get  '/dizr',    to: 'static_pages#dizr'
  get  '/rusers',  to: 'static_pages#rusers'
  get  '/rposts',  to: 'static_pages#rposts'
  get  '/rlikes',  to: 'static_pages#rlikes'
  get  '/rrel',  to: 'static_pages#rrel'
  get  '/rfrie',  to: 'static_pages#rfrie'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/pack'   , to: 'static_pages#pack'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/users',    to: 'users#index'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  post   '/'      ,to: 'microposts#create'

  
begin
  resources :users do
    member do
      get :following, :followers, :friends , :request_friends
    end
  end
end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :microposts,          only: [:create, :destroy] do
    member do
      get :like
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
  resources :friendships,         only: [:create, :destroy, :update]
  resources :likes,               only: [:create]
end 

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, url: root_path, html: { multipart: true  }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  
  <ul class="list-inline list-unstyled">
    <li>
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
    </li>
    <li><%= f.submit "Post", class: "btn btn-primary" %></li>
  </ul>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <% if @user.super_user? %>
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      followers
    </a>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>