config/routes.rb
  Rails.application.routes.draw do
    

  get 'likes/create'

  get 'likes/delete'

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/dize',    to: 'static_pages#dize'
  get  '/diza',    to: 'static_pages#diza'
  get  '/dizr',    to: 'static_pages#dizr'
  get  '/rusers',  to: 'static_pages#rusers'
  get  '/rposts',  to: 'static_pages#rposts'
  get  '/rlikes',  to: 'static_pages#rlikes'
  get  '/rrel',  to: 'static_pages#rrel'
  get  '/rfrie',  to: 'static_pages#rfrie'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/pack'   , to: 'static_pages#pack'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/users',    to: 'users#index'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  post   '/'      ,to: 'microposts#create'

  
begin
  resources :users do
    member do
      get :following, :followers, :friends , :request_friends
    end
  end
end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :microposts,          only: [:create, :destroy] do
    member do
      get :like
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
  resources :friendships,         only: [:create, :destroy, :update]
  resources :likes,               only: [:create]
end 

app/models/micropost.rb
class Micropost < ApplicationRecord
  mount_uploader :picture, PictureUploader
  
  belongs_to :user
  has_one :place
  
  has_many :likes
  has_many :liker, :through => :likes ,:source => :user
  
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  
  
  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :like]
  before_action :correct_user,   only: :destroy
  
  
  
  def like
    post=Micropost.find(params[:id])
    #@likes = Like.where(:micropost_id => params[:id])
    #@likers = @likes.find_liker.paginate(page: params[:page])
    likers_ids="SELECT user_id FROM likes WHERE micropost_id= ?"
    @likers= User.where("id IN ( #{likers_ids})",post.id).paginate(page: params[:page])
    render 'show_likes'
  end
  
  def unlike(user)
  end


  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items=current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private
  
    def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
    end

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) || (current_user && current_user.admin?) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
    <% if logged_in? %>
      <%= form_for(micropost.likes.build, remote:true) do |f| %>
        <div><%= hidden_field_tag :user, current_user.id %></div>
        <div> <%= hidden_field_tag :micro , micropost.id %> </div>
        <%= f.submit "like", class: "btn btn-primary reduce" %>
      <% end %>
      <%= link_to 'show likes', like_micropost_path(micropost.id) %>
    <% end %>
  </span>
</li>

app/views/microposts/show_likes.html.erb
<% provide(:title, 'All Requests') %>
<h1>Your Likes</h1>
<% if @likers.any? %>
  <div class="user_avatars">
    <% @likers.each do |user| %>
      <%= link_to gravatar_for(user, size: 30), user %>
      <%= user.name %>
    <% end %>
  </div>
<% end %>