config/routes.rb
  Rails.application.routes.draw do
    

  get 'likes/create'

  get 'likes/delete'

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/dize',    to: 'static_pages#dize'
  get  '/diza',    to: 'static_pages#diza'
  get  '/dizr',    to: 'static_pages#dizr'
  get  '/rusers',  to: 'static_pages#rusers'
  get  '/rposts',  to: 'static_pages#rposts'
  get  '/rlikes',  to: 'static_pages#rlikes'
  get  '/rrel',  to: 'static_pages#rrel'
  get  '/rfrie',  to: 'static_pages#rfrie'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/pack'   , to: 'static_pages#pack'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/users',    to: 'users#index'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  post   '/'      ,to: 'microposts#create'

  
begin
  resources :users do
    member do
      get :following, :followers, :friends , :request_friends
    end
  end
end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :microposts,          only: [:create, :destroy] do
    member do
      get :like
    end
  end
  
  resources :relationships,       only: [:create, :destroy]
  resources :friendships,         only: [:create, :destroy, :update]
  resources :likes,               only: [:create]
end 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://triptrack-ggd94.c9users.io/">TripTrack</a>
    by <a href="https://triptrack-ggd94.c9users.io/">Massimiliano Cestra & Giulia Giugno</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TripTrack", root_path, id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
           <!--glyphicon glyphicon-user-->
          <li><%= link_to "Friends", friends_user_path(current_user) %></li>
          <li><%= link_to "Search Users",users_path %></li>
          <li><%= link_to "Requests" , request_friends_user_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
                                      

                                           
      
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>



<%= csrf_meta_tags %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html >
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <% if logged_in? %>
      <script>
        var id = <%= current_user.id %>
        listen(id);
      </script>
    <% end %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}")%>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>

</html>